/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ExtensionRemovedRouteImport } from './routes/extension-removed'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ApiPublicCreditsRouteImport } from './routes/api/public/credits'
import { Route as ApiPublicUserCookiesRouteImport } from './routes/api/public/user/cookies'
import { Route as ApiPublicExtensionVideoSaveRouteImport } from './routes/api/public/extension/video-save'
import { Route as ApiPublicExtensionVerifyRouteImport } from './routes/api/public/extension/verify'
import { Route as ApiPublicExtensionIdentityRouteImport } from './routes/api/public/extension/identity'
import { Route as ApiPublicExtensionGenerateRouteImport } from './routes/api/public/extension/generate'
import { Route as ApiPublicExtensionDeductRouteImport } from './routes/api/public/extension/deduct'
import { Route as ApiPublicExtensionCookieVersionRouteImport } from './routes/api/public/extension/cookie-version'
import { Route as ApiPublicAuthSignupRouteImport } from './routes/api/public/auth/signup'
import { Route as ApiPublicAuthSendVerificationRouteImport } from './routes/api/public/auth/send-verification'
import { Route as ApiPublicAuthResetRequestRouteImport } from './routes/api/public/auth/reset-request'
import { Route as ApiPublicAuthResetRouteImport } from './routes/api/public/auth/reset'
import { Route as ApiPublicAuthRefreshRouteImport } from './routes/api/public/auth/refresh'
import { Route as ApiPublicAuthLoginRouteImport } from './routes/api/public/auth/login'
import { Route as ApiPublicAuthConfirmRouteImport } from './routes/api/public/auth/confirm'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtensionRemovedRoute = ExtensionRemovedRouteImport.update({
  id: '/extension-removed',
  path: '/extension-removed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicCreditsRoute = ApiPublicCreditsRouteImport.update({
  id: '/api/public/credits',
  path: '/api/public/credits',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicUserCookiesRoute = ApiPublicUserCookiesRouteImport.update({
  id: '/api/public/user/cookies',
  path: '/api/public/user/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicExtensionVideoSaveRoute =
  ApiPublicExtensionVideoSaveRouteImport.update({
    id: '/api/public/extension/video-save',
    path: '/api/public/extension/video-save',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicExtensionVerifyRoute =
  ApiPublicExtensionVerifyRouteImport.update({
    id: '/api/public/extension/verify',
    path: '/api/public/extension/verify',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicExtensionIdentityRoute =
  ApiPublicExtensionIdentityRouteImport.update({
    id: '/api/public/extension/identity',
    path: '/api/public/extension/identity',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicExtensionGenerateRoute =
  ApiPublicExtensionGenerateRouteImport.update({
    id: '/api/public/extension/generate',
    path: '/api/public/extension/generate',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicExtensionDeductRoute =
  ApiPublicExtensionDeductRouteImport.update({
    id: '/api/public/extension/deduct',
    path: '/api/public/extension/deduct',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicExtensionCookieVersionRoute =
  ApiPublicExtensionCookieVersionRouteImport.update({
    id: '/api/public/extension/cookie-version',
    path: '/api/public/extension/cookie-version',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAuthSignupRoute = ApiPublicAuthSignupRouteImport.update({
  id: '/api/public/auth/signup',
  path: '/api/public/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAuthSendVerificationRoute =
  ApiPublicAuthSendVerificationRouteImport.update({
    id: '/api/public/auth/send-verification',
    path: '/api/public/auth/send-verification',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAuthResetRequestRoute =
  ApiPublicAuthResetRequestRouteImport.update({
    id: '/api/public/auth/reset-request',
    path: '/api/public/auth/reset-request',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAuthResetRoute = ApiPublicAuthResetRouteImport.update({
  id: '/api/public/auth/reset',
  path: '/api/public/auth/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAuthRefreshRoute = ApiPublicAuthRefreshRouteImport.update({
  id: '/api/public/auth/refresh',
  path: '/api/public/auth/refresh',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAuthLoginRoute = ApiPublicAuthLoginRouteImport.update({
  id: '/api/public/auth/login',
  path: '/api/public/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAuthConfirmRoute = ApiPublicAuthConfirmRouteImport.update({
  id: '/api/public/auth/confirm',
  path: '/api/public/auth/confirm',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin-login': typeof AdminLoginRoute
  '/auth': typeof AuthRoute
  '/extension-removed': typeof ExtensionRemovedRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/api/public/credits': typeof ApiPublicCreditsRoute
  '/api/public/auth/confirm': typeof ApiPublicAuthConfirmRoute
  '/api/public/auth/login': typeof ApiPublicAuthLoginRoute
  '/api/public/auth/refresh': typeof ApiPublicAuthRefreshRoute
  '/api/public/auth/reset': typeof ApiPublicAuthResetRoute
  '/api/public/auth/reset-request': typeof ApiPublicAuthResetRequestRoute
  '/api/public/auth/send-verification': typeof ApiPublicAuthSendVerificationRoute
  '/api/public/auth/signup': typeof ApiPublicAuthSignupRoute
  '/api/public/extension/cookie-version': typeof ApiPublicExtensionCookieVersionRoute
  '/api/public/extension/deduct': typeof ApiPublicExtensionDeductRoute
  '/api/public/extension/generate': typeof ApiPublicExtensionGenerateRoute
  '/api/public/extension/identity': typeof ApiPublicExtensionIdentityRoute
  '/api/public/extension/verify': typeof ApiPublicExtensionVerifyRoute
  '/api/public/extension/video-save': typeof ApiPublicExtensionVideoSaveRoute
  '/api/public/user/cookies': typeof ApiPublicUserCookiesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-login': typeof AdminLoginRoute
  '/auth': typeof AuthRoute
  '/extension-removed': typeof ExtensionRemovedRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/api/public/credits': typeof ApiPublicCreditsRoute
  '/api/public/auth/confirm': typeof ApiPublicAuthConfirmRoute
  '/api/public/auth/login': typeof ApiPublicAuthLoginRoute
  '/api/public/auth/refresh': typeof ApiPublicAuthRefreshRoute
  '/api/public/auth/reset': typeof ApiPublicAuthResetRoute
  '/api/public/auth/reset-request': typeof ApiPublicAuthResetRequestRoute
  '/api/public/auth/send-verification': typeof ApiPublicAuthSendVerificationRoute
  '/api/public/auth/signup': typeof ApiPublicAuthSignupRoute
  '/api/public/extension/cookie-version': typeof ApiPublicExtensionCookieVersionRoute
  '/api/public/extension/deduct': typeof ApiPublicExtensionDeductRoute
  '/api/public/extension/generate': typeof ApiPublicExtensionGenerateRoute
  '/api/public/extension/identity': typeof ApiPublicExtensionIdentityRoute
  '/api/public/extension/verify': typeof ApiPublicExtensionVerifyRoute
  '/api/public/extension/video-save': typeof ApiPublicExtensionVideoSaveRoute
  '/api/public/user/cookies': typeof ApiPublicUserCookiesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/auth': typeof AuthRoute
  '/extension-removed': typeof ExtensionRemovedRoute
  '/signup': typeof SignupRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/api/public/credits': typeof ApiPublicCreditsRoute
  '/api/public/auth/confirm': typeof ApiPublicAuthConfirmRoute
  '/api/public/auth/login': typeof ApiPublicAuthLoginRoute
  '/api/public/auth/refresh': typeof ApiPublicAuthRefreshRoute
  '/api/public/auth/reset': typeof ApiPublicAuthResetRoute
  '/api/public/auth/reset-request': typeof ApiPublicAuthResetRequestRoute
  '/api/public/auth/send-verification': typeof ApiPublicAuthSendVerificationRoute
  '/api/public/auth/signup': typeof ApiPublicAuthSignupRoute
  '/api/public/extension/cookie-version': typeof ApiPublicExtensionCookieVersionRoute
  '/api/public/extension/deduct': typeof ApiPublicExtensionDeductRoute
  '/api/public/extension/generate': typeof ApiPublicExtensionGenerateRoute
  '/api/public/extension/identity': typeof ApiPublicExtensionIdentityRoute
  '/api/public/extension/verify': typeof ApiPublicExtensionVerifyRoute
  '/api/public/extension/video-save': typeof ApiPublicExtensionVideoSaveRoute
  '/api/public/user/cookies': typeof ApiPublicUserCookiesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin-login'
    | '/auth'
    | '/extension-removed'
    | '/signup'
    | '/admin'
    | '/dashboard'
    | '/api/public/credits'
    | '/api/public/auth/confirm'
    | '/api/public/auth/login'
    | '/api/public/auth/refresh'
    | '/api/public/auth/reset'
    | '/api/public/auth/reset-request'
    | '/api/public/auth/send-verification'
    | '/api/public/auth/signup'
    | '/api/public/extension/cookie-version'
    | '/api/public/extension/deduct'
    | '/api/public/extension/generate'
    | '/api/public/extension/identity'
    | '/api/public/extension/verify'
    | '/api/public/extension/video-save'
    | '/api/public/user/cookies'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-login'
    | '/auth'
    | '/extension-removed'
    | '/signup'
    | '/admin'
    | '/dashboard'
    | '/api/public/credits'
    | '/api/public/auth/confirm'
    | '/api/public/auth/login'
    | '/api/public/auth/refresh'
    | '/api/public/auth/reset'
    | '/api/public/auth/reset-request'
    | '/api/public/auth/send-verification'
    | '/api/public/auth/signup'
    | '/api/public/extension/cookie-version'
    | '/api/public/extension/deduct'
    | '/api/public/extension/generate'
    | '/api/public/extension/identity'
    | '/api/public/extension/verify'
    | '/api/public/extension/video-save'
    | '/api/public/user/cookies'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin-login'
    | '/auth'
    | '/extension-removed'
    | '/signup'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/api/public/credits'
    | '/api/public/auth/confirm'
    | '/api/public/auth/login'
    | '/api/public/auth/refresh'
    | '/api/public/auth/reset'
    | '/api/public/auth/reset-request'
    | '/api/public/auth/send-verification'
    | '/api/public/auth/signup'
    | '/api/public/extension/cookie-version'
    | '/api/public/extension/deduct'
    | '/api/public/extension/generate'
    | '/api/public/extension/identity'
    | '/api/public/extension/verify'
    | '/api/public/extension/video-save'
    | '/api/public/user/cookies'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  AuthRoute: typeof AuthRoute
  ExtensionRemovedRoute: typeof ExtensionRemovedRoute
  SignupRoute: typeof SignupRoute
  ApiPublicCreditsRoute: typeof ApiPublicCreditsRoute
  ApiPublicAuthConfirmRoute: typeof ApiPublicAuthConfirmRoute
  ApiPublicAuthLoginRoute: typeof ApiPublicAuthLoginRoute
  ApiPublicAuthRefreshRoute: typeof ApiPublicAuthRefreshRoute
  ApiPublicAuthResetRoute: typeof ApiPublicAuthResetRoute
  ApiPublicAuthResetRequestRoute: typeof ApiPublicAuthResetRequestRoute
  ApiPublicAuthSendVerificationRoute: typeof ApiPublicAuthSendVerificationRoute
  ApiPublicAuthSignupRoute: typeof ApiPublicAuthSignupRoute
  ApiPublicExtensionCookieVersionRoute: typeof ApiPublicExtensionCookieVersionRoute
  ApiPublicExtensionDeductRoute: typeof ApiPublicExtensionDeductRoute
  ApiPublicExtensionGenerateRoute: typeof ApiPublicExtensionGenerateRoute
  ApiPublicExtensionIdentityRoute: typeof ApiPublicExtensionIdentityRoute
  ApiPublicExtensionVerifyRoute: typeof ApiPublicExtensionVerifyRoute
  ApiPublicExtensionVideoSaveRoute: typeof ApiPublicExtensionVideoSaveRoute
  ApiPublicUserCookiesRoute: typeof ApiPublicUserCookiesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extension-removed': {
      id: '/extension-removed'
      path: '/extension-removed'
      fullPath: '/extension-removed'
      preLoaderRoute: typeof ExtensionRemovedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/credits': {
      id: '/api/public/credits'
      path: '/api/public/credits'
      fullPath: '/api/public/credits'
      preLoaderRoute: typeof ApiPublicCreditsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/user/cookies': {
      id: '/api/public/user/cookies'
      path: '/api/public/user/cookies'
      fullPath: '/api/public/user/cookies'
      preLoaderRoute: typeof ApiPublicUserCookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/extension/video-save': {
      id: '/api/public/extension/video-save'
      path: '/api/public/extension/video-save'
      fullPath: '/api/public/extension/video-save'
      preLoaderRoute: typeof ApiPublicExtensionVideoSaveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/extension/verify': {
      id: '/api/public/extension/verify'
      path: '/api/public/extension/verify'
      fullPath: '/api/public/extension/verify'
      preLoaderRoute: typeof ApiPublicExtensionVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/extension/identity': {
      id: '/api/public/extension/identity'
      path: '/api/public/extension/identity'
      fullPath: '/api/public/extension/identity'
      preLoaderRoute: typeof ApiPublicExtensionIdentityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/extension/generate': {
      id: '/api/public/extension/generate'
      path: '/api/public/extension/generate'
      fullPath: '/api/public/extension/generate'
      preLoaderRoute: typeof ApiPublicExtensionGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/extension/deduct': {
      id: '/api/public/extension/deduct'
      path: '/api/public/extension/deduct'
      fullPath: '/api/public/extension/deduct'
      preLoaderRoute: typeof ApiPublicExtensionDeductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/extension/cookie-version': {
      id: '/api/public/extension/cookie-version'
      path: '/api/public/extension/cookie-version'
      fullPath: '/api/public/extension/cookie-version'
      preLoaderRoute: typeof ApiPublicExtensionCookieVersionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/auth/signup': {
      id: '/api/public/auth/signup'
      path: '/api/public/auth/signup'
      fullPath: '/api/public/auth/signup'
      preLoaderRoute: typeof ApiPublicAuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/auth/send-verification': {
      id: '/api/public/auth/send-verification'
      path: '/api/public/auth/send-verification'
      fullPath: '/api/public/auth/send-verification'
      preLoaderRoute: typeof ApiPublicAuthSendVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/auth/reset-request': {
      id: '/api/public/auth/reset-request'
      path: '/api/public/auth/reset-request'
      fullPath: '/api/public/auth/reset-request'
      preLoaderRoute: typeof ApiPublicAuthResetRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/auth/reset': {
      id: '/api/public/auth/reset'
      path: '/api/public/auth/reset'
      fullPath: '/api/public/auth/reset'
      preLoaderRoute: typeof ApiPublicAuthResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/auth/refresh': {
      id: '/api/public/auth/refresh'
      path: '/api/public/auth/refresh'
      fullPath: '/api/public/auth/refresh'
      preLoaderRoute: typeof ApiPublicAuthRefreshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/auth/login': {
      id: '/api/public/auth/login'
      path: '/api/public/auth/login'
      fullPath: '/api/public/auth/login'
      preLoaderRoute: typeof ApiPublicAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/auth/confirm': {
      id: '/api/public/auth/confirm'
      path: '/api/public/auth/confirm'
      fullPath: '/api/public/auth/confirm'
      preLoaderRoute: typeof ApiPublicAuthConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  AuthRoute: AuthRoute,
  ExtensionRemovedRoute: ExtensionRemovedRoute,
  SignupRoute: SignupRoute,
  ApiPublicCreditsRoute: ApiPublicCreditsRoute,
  ApiPublicAuthConfirmRoute: ApiPublicAuthConfirmRoute,
  ApiPublicAuthLoginRoute: ApiPublicAuthLoginRoute,
  ApiPublicAuthRefreshRoute: ApiPublicAuthRefreshRoute,
  ApiPublicAuthResetRoute: ApiPublicAuthResetRoute,
  ApiPublicAuthResetRequestRoute: ApiPublicAuthResetRequestRoute,
  ApiPublicAuthSendVerificationRoute: ApiPublicAuthSendVerificationRoute,
  ApiPublicAuthSignupRoute: ApiPublicAuthSignupRoute,
  ApiPublicExtensionCookieVersionRoute: ApiPublicExtensionCookieVersionRoute,
  ApiPublicExtensionDeductRoute: ApiPublicExtensionDeductRoute,
  ApiPublicExtensionGenerateRoute: ApiPublicExtensionGenerateRoute,
  ApiPublicExtensionIdentityRoute: ApiPublicExtensionIdentityRoute,
  ApiPublicExtensionVerifyRoute: ApiPublicExtensionVerifyRoute,
  ApiPublicExtensionVideoSaveRoute: ApiPublicExtensionVideoSaveRoute,
  ApiPublicUserCookiesRoute: ApiPublicUserCookiesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
